version: '3'
services:
  redis1:
    build : ./redis-master
    ports:
      - 7001:6379
  redis2:
    build : ./redis-slave
    ports:
      - 7002:6379
    depends_on:
      - redis1
    environment:
      REDIS_MASTER_ADDRESS: redis1
      REDIS_MASTER_PORT: 6379
  sentinel1:
    build : ./redis-sentinel
    depends_on:
      - redis1
    ports:
      - 8001:26379
    environment:
      REDIS_MASTER_ADDRESS: redis1
      REDIS_MASTER_PORT: 6379
  sentinel2:
    build : ./redis-sentinel
    depends_on:
      - redis1
    ports:
      - 8002:26379
    environment:
      REDIS_MASTER_ADDRESS: redis1
      REDIS_MASTER_PORT: 6379
